-- Winter Arc Supabase schema
-- Run this in Supabase SQL Editor after creating your project.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  start_date date default current_date,
  target_weight numeric default 85,
  created_at timestamptz default now()
);

create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null,
  weight numeric default 103,
  target_weight numeric default 85,
  water numeric default 0,
  water_target numeric default 3,
  protein numeric default 0,
  protein_target numeric default 150,
  steps integer default 0,
  steps_target integer default 10000,
  workout boolean default false,
  workout_type text default 'Gym',
  workout_minutes integer default 0,
  run boolean default false,
  run_km numeric default 0,
  sleep numeric default 0,
  sleep_target numeric default 8,
  coding_minutes integer default 0,
  coding_target integer default 120,
  job_applications integer default 0,
  job_target integer default 10,
  job_minutes integer default 0,
  no_junk boolean default false,
  no_sugar boolean default false,
  no_phone_eating boolean default false,
  hair_care boolean default false,
  focus_self boolean default false,
  note text,
  daily_score integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, log_date)
);

alter table public.profiles enable row level security;
alter table public.daily_logs enable row level security;

create policy "Users can view own profile" on public.profiles
for select using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
for insert with check (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
for update using (auth.uid() = id);

create policy "Users can view own logs" on public.daily_logs
for select using (auth.uid() = user_id);

create policy "Users can insert own logs" on public.daily_logs
for insert with check (auth.uid() = user_id);

create policy "Users can update own logs" on public.daily_logs
for update using (auth.uid() = user_id);

create policy "Users can delete own logs" on public.daily_logs
for delete using (auth.uid() = user_id);

-- Optional profile auto-create trigger
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();